### ISSUE TITLE
About the train and test split

### ISSUE THREAD

**Issue by yyyykf** [MEPP-team/Graphics-LPIPS#1]
Hello, as you mentioned in your paper,   
"_80 % of the stimuli in the dataset (about 2400) are used for training
and 20 % for testing. The dataset is randomly split by source model
ensuring that no 3D model is used for both training and testing. As
a result, 44 source models out of 55 were included in the training
while the rest were used for testing. We used k-fold cross-validation
and generated 5 different splits. We report the performances over
the 5 folds in the next subsection and chose a representative fold
with average performances for all the subsequent evaluations_",   
could you please give me **the  5 different splits** you used and shown in your paper so that I can compare other methods with your method?

**Comment by jdelanoy** [comment]
Hello, We just added the splits in the repo. You can find them in the folder datasets/folds. You have 2 csv per folds (one for training, one for testing), they are organized the same way as the ones provided with the dataset and can be used directly with the train.py script.
